/**
 * Deterministic Drizzle + Server Actions codegen from a schema map.
 * Prefer this over LLM-authored schema.ts (no hallucinated tables/columns).
 */
import type { DatabaseSchemaMap, PgDataType, SchemaColumn, SchemaTable } from "./types";

function toCamel(name: string): string {
  return name.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

function toPascal(name: string): string {
  const c = toCamel(name);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function drizzleCol(col: SchemaColumn): string {
  const n = col.name;
  const chain: string[] = [];

  const typeExpr = (t: PgDataType): string => {
    switch (t) {
      case "uuid":
        return `uuid("${n}")`;
      case "text":
        return `text("${n}")`;
      case "varchar":
        return col.maxLength
          ? `varchar("${n}", { length: ${col.maxLength} })`
          : `varchar("${n}")`;
      case "integer":
        return `integer("${n}")`;
      case "bigint":
        return `bigint("${n}", { mode: "number" })`;
      case "boolean":
        return `boolean("${n}")`;
      case "numeric":
        return `numeric("${n}")`;
      case "real":
        return `real("${n}")`;
      case "double":
        return `doublePrecision("${n}")`;
      case "timestamp":
        return `timestamp("${n}")`;
      case "timestamptz":
        return `timestamp("${n}", { withTimezone: true })`;
      case "date":
        return `date("${n}")`;
      case "json":
      case "jsonb":
        return `jsonb("${n}")`;
      default:
        return `text("${n}")`;
    }
  };

  let expr = typeExpr(col.dataType);
  if (col.isPrimaryKey) {
    // uuid PKs often use defaultRandom
    if (col.dataType === "uuid") {
      expr += ".defaultRandom().primaryKey()";
    } else {
      expr += ".primaryKey()";
    }
  } else {
    if (!col.nullable) expr += ".notNull()";
  }

  chain.push(`    ${toCamel(n)}: ${expr},`);
  return chain.join("\n");
}

function tableExportName(table: SchemaTable): string {
  return toCamel(table.name);
}

/** lib/db/schema.ts */
export function generateDrizzleSchemaTs(schema: DatabaseSchemaMap): string {
  const imports = new Set<string>(["pgTable"]);
  for (const t of schema.tables) {
    for (const c of t.columns) {
      switch (c.dataType) {
        case "uuid":
          imports.add("uuid");
          break;
        case "text":
          imports.add("text");
          break;
        case "varchar":
          imports.add("varchar");
          break;
        case "integer":
          imports.add("integer");
          break;
        case "bigint":
          imports.add("bigint");
          break;
        case "boolean":
          imports.add("boolean");
          break;
        case "numeric":
          imports.add("numeric");
          break;
        case "real":
          imports.add("real");
          break;
        case "double":
          imports.add("doublePrecision");
          break;
        case "timestamp":
        case "timestamptz":
          imports.add("timestamp");
          break;
        case "date":
          imports.add("date");
          break;
        case "json":
        case "jsonb":
          imports.add("jsonb");
          break;
        default:
          imports.add("text");
      }
    }
  }

  const importLine = `import { ${[...imports].sort().join(", ")} } from "drizzle-orm/pg-core";\n`;

  const tables = schema.tables.map((t) => {
    const cols = t.columns.map(drizzleCol).join("\n");
    const exp = tableExportName(t);
    return `/** Table: public.${t.name} */\nexport const ${exp} = pgTable("${t.name}", {\n${cols}\n});\n`;
  });

  return (
    `/**\n * Drizzle schema — generated by Shipboard from your Postgres introspection.\n` +
    ` * Provider: ${schema.provider} · ${schema.tableCount} table(s) · ${schema.introspectedAt}\n` +
    ` * Do not hand-edit blindly; re-introspect in Shipboard or adjust migrations intentionally.\n */\n` +
    importLine +
    `\n` +
    (tables.length
      ? tables.join("\n")
      : `// No public tables found during introspection.\n`)
  );
}

/** lib/db/index.ts */
export function generateDbClientTs(): string {
  return `import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "./schema";

/**
 * Server-only DB client (Neon HTTP + Drizzle).
 * Requires DATABASE_URL in the environment.
 */
export function getDb() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL is not set. Copy .env.example → .env.local and paste your Neon/Supabase connection string."
    );
  }
  const sql = neon(url);
  return drizzle(sql, { schema });
}

export type Db = ReturnType<typeof getDb>;
export { schema };
`;
}

/** app/actions.ts — basic list/get Server Actions per table */
export function generateServerActionsTs(schema: DatabaseSchemaMap): string {
  if (!schema.tables.length) {
    return `"use server";

/** No tables introspected — add tables in Postgres and re-export from Shipboard. */
export async function healthCheck() {
  return { ok: true as const, tables: [] as string[] };
}
`;
  }

  const tableImports = schema.tables.map((t) => tableExportName(t)).join(", ");
  const actions: string[] = [];

  for (const t of schema.tables) {
    const exp = tableExportName(t);
    const pascal = toPascal(t.name);
    const pk = t.columns.find((c) => c.isPrimaryKey) || t.columns[0];
    const pkField = pk ? toCamel(pk.name) : "id";

    actions.push(`
/** List rows from public.${t.name} */
export async function list${pascal}(limit = 50) {
  const db = getDb();
  const rows = await db.select().from(${exp}).limit(Math.min(Math.max(limit, 1), 200));
  return rows;
}

/** Get one row from public.${t.name} by primary key */
export async function get${pascal}ById(id: string | number) {
  const db = getDb();
  const rows = await db.select().from(${exp}).where(eq(${exp}.${pkField}, id as never)).limit(1);
  return rows[0] ?? null;
}
`);
  }

  return `"use server";

/**
 * Next.js Server Actions — generated by Shipboard BYOB.
 * Wire these into client components via forms / useTransition.
 */
import { eq } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { ${tableImports} } from "@/lib/db/schema";
${actions.join("\n")}
export async function listTables() {
  return ${JSON.stringify(schema.tables.map((t) => t.name))} as const;
}
`;
}

/** Sample seed rows for preview / docs */
export function generatePreviewMocksTs(schema: DatabaseSchemaMap): string {
  const samples: Record<string, Record<string, unknown>[]> = {};
  for (const t of schema.tables) {
    samples[t.name] = [sampleRow(t), sampleRow(t, 2)];
  }
  return `/**
 * Preview / Storybook-style mock rows shaped like your Drizzle tables.
 * Studio iframe cannot hit Postgres — use these seeds in UI until ship.
 */
export const PREVIEW_DB_MOCKS = ${JSON.stringify(samples, null, 2)} as const;

export type PreviewTableName = keyof typeof PREVIEW_DB_MOCKS;

export function previewRows(table: string): Record<string, unknown>[] {
  const key = table as PreviewTableName;
  return (PREVIEW_DB_MOCKS[key] as Record<string, unknown>[] | undefined) ?? [];
}
`;
}

function sampleRow(t: SchemaTable, n = 1): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  for (const c of t.columns) {
    const k = c.name;
    if (c.isPrimaryKey && c.dataType === "uuid") {
      row[k] = `00000000-0000-4000-8000-00000000000${n}`;
    } else if (c.isPrimaryKey) {
      row[k] = n;
    } else {
      switch (c.dataType) {
        case "boolean":
          row[k] = n % 2 === 0;
          break;
        case "integer":
        case "bigint":
        case "numeric":
        case "real":
        case "double":
          row[k] = n * 10;
          break;
        case "timestamptz":
        case "timestamp":
        case "date":
          row[k] = new Date().toISOString();
          break;
        case "json":
        case "jsonb":
          row[k] = { demo: true, n };
          break;
        default:
          row[k] = `${t.name}_${k}_${n}`;
      }
    }
  }
  return row;
}

export function generateEnvExample(schema: DatabaseSchemaMap): string {
  return `# Shipboard BYOB — database
# Paste your Neon or Supabase connection string (pooled or direct).
DATABASE_URL=postgresql://user:password@host/db?sslmode=require

# Introspected: ${schema.provider} · ${schema.tableCount} table(s)
# Host hint: ${schema.hostHint || "(unknown)"}
# Tables: ${schema.tables.map((t) => t.name).join(", ") || "(none)"}
`;
}

/** package.json dependency bumps for BYOB ship */
export function byobPackageDependencies(): Record<string, string> {
  return {
    "@neondatabase/serverless": "^1.0.0",
    "drizzle-orm": "^0.38.3",
  };
}

export function byobDevDependencies(): Record<string, string> {
  return {
    "drizzle-kit": "^0.30.1",
  };
}

/**
 * Full file set for Next ship scaffold when a schema map is present.
 */
export function buildByobShipFiles(
  schema: DatabaseSchemaMap
): { path: string; content: string }[] {
  return [
    { path: "lib/db/schema.ts", content: generateDrizzleSchemaTs(schema) },
    { path: "lib/db/index.ts", content: generateDbClientTs() },
    { path: "app/actions.ts", content: generateServerActionsTs(schema) },
    { path: "lib/db/preview-mocks.ts", content: generatePreviewMocksTs(schema) },
    { path: ".env.example", content: generateEnvExample(schema) },
  ];
}
