/**
 * Phase D/E — Agent X-Ray telemetry for ejected apps.
 * Tool wrappers + run-level usage/cost (Vercel AI SDK onFinish).
 */

/** Rough USD estimates — override via env in production. */
export function generateAgentTelemetryTs(): string {
  return `/**
 * Agent X-Ray — tool tracing + token/cost observability.
 * Generated by Shipboard Phase D.
 *
 * Multi-tenant ingest (required for production):
 *   SHIPBOARD_TELEMETRY_URL=https://your-host/api/telemetry/events
 *   SHIPBOARD_INGEST_KEY=sb_ing_…   (Authorization: Bearer)
 *   SHIPBOARD_PROJECT_ID=…          (optional consistency check)
 * Optional cost rates (USD per 1M tokens):
 *   OPENAI_INPUT_USD_PER_1M=0.15
 *   OPENAI_OUTPUT_USD_PER_1M=0.60
 */

export type TelemetryEvent = {
  type:
    | "tool_start"
    | "tool_success"
    | "tool_error"
    | "run_finish"
    | "run_usage";
  tool: string;
  args?: unknown;
  resultPreview?: unknown;
  error?: string;
  latencyMs?: number;
  runId?: string;
  timestamp: string;
  /** Token / cost fields (especially run_finish) */
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  estimatedCostUsd?: number;
  model?: string;
  meta?: Record<string, unknown>;
};

export type TraceableTool = {
  description?: string;
  parameters?: unknown;
  execute: (args: any, options?: any) => Promise<any> | any;
  [key: string]: unknown;
};

export type LanguageModelUsage = {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
};

function previewPayload(value: unknown, max = 2000): unknown {
  try {
    const s = JSON.stringify(value);
    if (s.length <= max) return value;
    return { _truncated: true, preview: s.slice(0, max) };
  } catch {
    return String(value);
  }
}

function rate(envKey: string, fallback: number): number {
  const raw = process.env[envKey];
  if (!raw) return fallback;
  const n = Number(raw);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}

/** Estimate USD from usage (defaults ≈ gpt-4o-mini ballpark). */
export function estimateCostUsd(usage: LanguageModelUsage | undefined | null): number | undefined {
  if (!usage) return undefined;
  const inputPer1M = rate("OPENAI_INPUT_USD_PER_1M", 0.15);
  const outputPer1M = rate("OPENAI_OUTPUT_USD_PER_1M", 0.6);
  const prompt = usage.promptTokens ?? 0;
  const completion = usage.completionTokens ?? 0;
  if (prompt === 0 && completion === 0 && !usage.totalTokens) return undefined;
  const cost =
    (prompt / 1_000_000) * inputPer1M + (completion / 1_000_000) * outputPer1M;
  return Math.round(cost * 1e6) / 1e6;
}

async function emit(event: TelemetryEvent): Promise<void> {
  const url = process.env.SHIPBOARD_TELEMETRY_URL;
  const ingestKey = process.env.SHIPBOARD_INGEST_KEY;
  if (url) {
    try {
      await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(ingestKey
            ? { Authorization: \`Bearer \${ingestKey}\` }
            : process.env.SHIPBOARD_TELEMETRY_TOKEN
              ? { Authorization: \`Bearer \${process.env.SHIPBOARD_TELEMETRY_TOKEN}\` }
              : {}),
        },
        body: JSON.stringify({
          ...event,
          projectId: process.env.SHIPBOARD_PROJECT_ID,
        }),
      });
      return;
    } catch {
      /* fall through */
    }
  }
  if (process.env.NODE_ENV !== "production") {
    const cost =
      event.estimatedCostUsd != null ? \` $\${event.estimatedCostUsd}\` : "";
    const tok =
      event.totalTokens != null ? \` \${event.totalTokens}tok\` : "";
    console.info(
      "[shipboard:telemetry]",
      event.type,
      event.tool,
      event.latencyMs ?? "",
      tok,
      cost,
      event.error ?? ""
    );
  }
}

export { emit as emitTelemetryEvent };

/** Wrap a single AI SDK tool with start/success/error tracing. */
export function withTracing<T extends TraceableTool>(
  name: string,
  tool: T,
  opts?: { runId?: string; meta?: Record<string, unknown> }
): T {
  const execute = tool.execute;
  if (typeof execute !== "function") return tool;

  return {
    ...tool,
    execute: async (args: unknown, context?: unknown) => {
      const start = performance.now();
      const runId = opts?.runId;
      await emit({
        type: "tool_start",
        tool: name,
        args: previewPayload(args),
        runId,
        timestamp: new Date().toISOString(),
        meta: opts?.meta,
      });
      try {
        const result = await execute(args, context);
        await emit({
          type: "tool_success",
          tool: name,
          args: previewPayload(args),
          resultPreview: previewPayload(result),
          latencyMs: Math.round(performance.now() - start),
          runId,
          timestamp: new Date().toISOString(),
          meta: opts?.meta,
        });
        return result;
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        await emit({
          type: "tool_error",
          tool: name,
          args: previewPayload(args),
          error: message,
          latencyMs: Math.round(performance.now() - start),
          runId,
          timestamp: new Date().toISOString(),
          meta: opts?.meta,
        });
        throw error;
      }
    },
  } as T;
}

/** Wrap a tools record: { listUsers: tool(...), ... } */
export function wrapToolsWithTracing<T extends Record<string, TraceableTool>>(
  tools: T,
  opts?: { runId?: string; meta?: Record<string, unknown> }
): T {
  const out = {} as T;
  for (const key of Object.keys(tools) as (keyof T)[]) {
    out[key] = withTracing(String(key), tools[key], opts);
  }
  return out;
}

/**
 * Call from streamText({ onFinish }) to record token usage + estimated cost.
 */
export async function reportRunUsage(opts: {
  runId?: string;
  model?: string;
  usage?: LanguageModelUsage | null;
  finishReason?: string;
  latencyMs?: number;
  meta?: Record<string, unknown>;
}): Promise<void> {
  const usage = opts.usage;
  const promptTokens = usage?.promptTokens;
  const completionTokens = usage?.completionTokens;
  const totalTokens =
    usage?.totalTokens ??
    (promptTokens != null || completionTokens != null
      ? (promptTokens ?? 0) + (completionTokens ?? 0)
      : undefined);
  const estimatedCostUsd = estimateCostUsd(usage ?? undefined);

  await emit({
    type: "run_finish",
    tool: "agent_run",
    runId: opts.runId,
    model: opts.model,
    promptTokens,
    completionTokens,
    totalTokens,
    estimatedCostUsd,
    latencyMs: opts.latencyMs,
    timestamp: new Date().toISOString(),
    meta: {
      ...opts.meta,
      finishReason: opts.finishReason,
    },
  });
}
`;
}

export function generateAgentEnvTelemetrySnippet(): string {
  return `# Telemetry (Phase D — optional)
# SHIPBOARD_TELEMETRY_URL=https://your-shipboard-host/api/telemetry/events
# SHIPBOARD_TELEMETRY_TOKEN=optional-bearer
# OPENAI_INPUT_USD_PER_1M=0.15
# OPENAI_OUTPUT_USD_PER_1M=0.60
`;
}
