/**
 * Phase D — Agent X-Ray telemetry for ejected apps.
 * Wraps Vercel AI SDK tools; fires to Shipboard or a custom endpoint.
 */

/** lib/agent/telemetry.ts */
export function generateAgentTelemetryTs(): string {
  return `/**
 * Agent X-Ray — wrap tools for latency / args / error tracing.
 * Generated by Shipboard Phase D.
 *
 * Set SHIPBOARD_TELEMETRY_URL (optional) to post events to your Shipboard
 * workspace or any HTTP collector. Falls back to console in development.
 */

export type TelemetryEvent = {
  type: "tool_start" | "tool_success" | "tool_error";
  tool: string;
  args?: unknown;
  resultPreview?: unknown;
  error?: string;
  latencyMs?: number;
  runId?: string;
  timestamp: string;
  meta?: Record<string, unknown>;
};

export type TraceableTool = {
  description?: string;
  parameters?: unknown;
  execute: (args: any, options?: any) => Promise<any> | any;
  [key: string]: unknown;
};

function previewPayload(value: unknown, max = 2000): unknown {
  try {
    const s = JSON.stringify(value);
    if (s.length <= max) return value;
    return { _truncated: true, preview: s.slice(0, max) };
  } catch {
    return String(value);
  }
}

async function emit(event: TelemetryEvent): Promise<void> {
  const url = process.env.SHIPBOARD_TELEMETRY_URL;
  if (url) {
    try {
      await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(process.env.SHIPBOARD_TELEMETRY_TOKEN
            ? { Authorization: \`Bearer \${process.env.SHIPBOARD_TELEMETRY_TOKEN}\` }
            : {}),
        },
        body: JSON.stringify(event),
      });
      return;
    } catch {
      /* fall through */
    }
  }
  if (process.env.NODE_ENV !== "production") {
    console.info("[shipboard:telemetry]", event.type, event.tool, event.latencyMs ?? "", event.error ?? "");
  }
}

/** Wrap a single AI SDK tool with start/success/error tracing. */
export function withTracing<T extends TraceableTool>(
  name: string,
  tool: T,
  opts?: { runId?: string; meta?: Record<string, unknown> }
): T {
  const execute = tool.execute;
  if (typeof execute !== "function") return tool;

  return {
    ...tool,
    execute: async (args: unknown, context?: unknown) => {
      const start = performance.now();
      const runId = opts?.runId;
      await emit({
        type: "tool_start",
        tool: name,
        args: previewPayload(args),
        runId,
        timestamp: new Date().toISOString(),
        meta: opts?.meta,
      });
      try {
        const result = await execute(args, context);
        await emit({
          type: "tool_success",
          tool: name,
          args: previewPayload(args),
          resultPreview: previewPayload(result),
          latencyMs: Math.round(performance.now() - start),
          runId,
          timestamp: new Date().toISOString(),
          meta: opts?.meta,
        });
        return result;
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        await emit({
          type: "tool_error",
          tool: name,
          args: previewPayload(args),
          error: message,
          latencyMs: Math.round(performance.now() - start),
          runId,
          timestamp: new Date().toISOString(),
          meta: opts?.meta,
        });
        throw error;
      }
    },
  } as T;
}

/** Wrap a tools record: { listUsers: tool(...), ... } */
export function wrapToolsWithTracing<T extends Record<string, TraceableTool>>(
  tools: T,
  opts?: { runId?: string; meta?: Record<string, unknown> }
): T {
  const out = {} as T;
  for (const key of Object.keys(tools) as (keyof T)[]) {
    out[key] = withTracing(String(key), tools[key], opts);
  }
  return out;
}
`;
}

export function generateAgentEnvTelemetrySnippet(): string {
  return `# Telemetry (Phase D — optional)
# SHIPBOARD_TELEMETRY_URL=https://your-shipboard-host/api/telemetry/events
# SHIPBOARD_TELEMETRY_TOKEN=optional-bearer
`;
}
